# Validação de títulos
extends: substitution
message: "Títulos devem seguir o padrão: número_idioma_tipo_nome (Ex: 01_PT_REF_MinhasAprovacoes)"
level: error
scope: text
pattern: '\d{2}_(PT|EN)_(REF|EXP|HOW)_[A-Za-z]+'

---
# Validação de code fences
extends: substitution
message: "Blocos de código devem usar três crases (```) e especificar a linguagem"
level: error
scope: raw
pattern: "^```[a-z]+$"

---
# Validação de links
extends: substitution
message: "Links devem usar o formato correto [texto](url)"
level: warning
scope: text
pattern: '\[([^\]]+)\]\(([^\)]+)\)'

---
# Validação de numeração em listas
extends: substitution
message: "Listas numeradas devem começar com '1.'"
level: warning
scope: text
pattern: '^\s*1\.'

---
# Validação de avisos e alertas
extends: substitution
message: "Avisos devem começar com 'Atenção:' ou 'Alerta!'"
level: warning
scope: text
pattern: '^(Atenção:|Alerta!)'

---
# Validação de extensões de arquivo
extends: substitution
message: "Extensões de arquivo devem usar code fences"
level: warning
scope: text
pattern: '`\.[a-z]+`'

---
# Validação de caminhos de arquivo
extends: substitution
message: "Caminhos de arquivo devem usar code fences"
level: warning
scope: text
pattern: '`([A-Za-z]:\\|\/)[^\s`]+'

---
# Validação de versões
extends: substitution
message: "Versões devem seguir o formato 'Versão X - Nome'"
level: error
scope: text
pattern: '^Versão \d+ - [A-Za-z\s]+'

---
# Validação de datas
extends: substitution
message: "Datas devem seguir o formato 'Mês DD, YYYY'"
level: warning
scope: text
pattern: '(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},\s+\d{4}'

---
# Validação de itálico
extends: substitution
message: "Palavras estrangeiras devem estar em itálico"
level: warning
scope: text
pattern: '(?<!_)\b(software|hardware|backup|login|logout|update|download|upload)\b(?!_)'